#! /usr/bin/env bash
# This script will apply xsl transformation on a svg file generated by Bob, to
# create import files used by Planner Interface.
set -e 

VERBOSE=false
xsl_verbose=""
sflag=false
DEST_DIR=`date +%Y%m%d%H%M`

# read the options
TEMP=`getopt -o s:d:v --long source:,verbose,dest_dir: -- "$@"`
eval set -- "$TEMP"

# extract options and their arguments into variables.
while true ; do
  case "$1" in
    -s|--source)
      SOURCE_FILE=$2; sflag=true; shift 2;;
    -v|--verbose)
      VERBOSE=true; xsl_verbose="-v"; shift;;
    -d|--dest_dir)
      DEST_DIR=$2; shift 2;;
    --) shift ; break ;;
      *) echo "Internal error!"; exit 1;;
  esac
done

if ! $sflag
then 
  echo "Argument -s or --source source_file is mandatary."
  exit -1

fi  

if [ ! -e $SOURCE_FILE ]
then
  echo "Bad argument value -s or --source. File $SOURCE_FILE does not exist."
  exit -1
fi


function headerVerbose {
  if $VERBOSE
  then
    echo 
    echo
    echo "==============================================="
    echo "Generation of $1 file"
    echo "==============================================="
  fi
}

headerVerbose station.xml
xsltproc $xsl_verbose -o station.xml  ../xsl/Gantt2Station.xsl  $SOURCE_FILE
headerVerbose qual.xml
xsltproc $xsl_verbose -o qual.xml     ../xsl/Gantt2Qual.xsl     $SOURCE_FILE
headerVerbose actc.xml
xsltproc $xsl_verbose -o acts.xml     ../xsl/Gantt2Acts.xsl     $SOURCE_FILE
headerVerbose trip.xml
xsltproc $xsl_verbose -o trip.xml     ../xsl/Gantt2Trip.xsl     $SOURCE_FILE
headerVerbose trip_sup.xml
xsltproc $xsl_verbose -o trip_sup.xml ../xsl/Gantt2Trip_sup.xsl $SOURCE_FILE

